theme: minima
title: Beloved
author: Toni Morrison
description: Set in the period after the American Civil War, the novel tells the story of a dysfunctional family of formerly enslaved people whose Cincinnati home is haunted by a malevolent spirit
